# Documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and Deploy app to GitHub Pages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code base
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          full_commit_message: 'deploy: publish app to GitHub Pages'
